/**
 * Application Permissions
 * 
 * This file contains all permission definitions used throughout the application.
 * Permissions are checked against the user's role permissions loaded from the backend.
 * 
 * IMPORTANT: These names must EXACTLY match the permission names in the database!
 */

export const PERMISSIONS = {
  // Admin panel access
  ACCESS_ADMIN_PANEL: "ACCESS_ADMIN_PANEL",
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  ACCESS_DASHBOARD_ROUTE: "ACCESS_DASHBOARD_ROUTE",
  
  // Sidebar menu visibility permissions (VIEW_*_MENU)
  VIEW_DASHBOARD_MENU: "VIEW_DASHBOARD_MENU",
  VIEW_PRODUCTS_MENU: "VIEW_PRODUCTS_MENU",
  VIEW_STOCK_MENU: "VIEW_STOCK_MENU",
  VIEW_SALES_MENU: "VIEW_SALES_MENU",
  VIEW_LOYALTY_MENU: "VIEW_LOYALTY_MENU",
  VIEW_USERS_MENU: "VIEW_USERS_MENU",
  VIEW_POSTS_MENU: "VIEW_POSTS_MENU",
  VIEW_REVIEWS_MENU: "VIEW_REVIEWS_MENU",
  VIEW_ROLES_MENU: "VIEW_ROLES_MENU",
  
  // Route/URL access permissions (ACCESS_*_ROUTE)
  ACCESS_PRODUCTS_ROUTE: "ACCESS_PRODUCTS_ROUTE",
  ACCESS_STOCK_ROUTE: "ACCESS_STOCK_ROUTE",
  ACCESS_SALES_ROUTE: "ACCESS_SALES_ROUTE",
  ACCESS_LOYALTY_ROUTE: "ACCESS_LOYALTY_ROUTE",
  ACCESS_USERS_ROUTE: "ACCESS_USERS_ROUTE",
  ACCESS_POSTS_ROUTE: "ACCESS_POSTS_ROUTE",
  ACCESS_REVIEWS_ROUTE: "ACCESS_REVIEWS_ROUTE",
  ACCESS_ROLES_ROUTE: "ACCESS_ROLES_ROUTE",
  
  // Users permissions
  VIEW_USERS: "VIEW_USERS",
  CREATE_USERS: "CREATE_USERS",
  UPDATE_USERS: "UPDATE_USERS",
  DELETE_USERS: "DELETE_USERS",

  // Roles permissions
  VIEW_ROLES: "VIEW_ROLES",
  CREATE_ROLES: "CREATE_ROLES",
  UPDATE_ROLES: "UPDATE_ROLES",
  DELETE_ROLES: "DELETE_ROLES",
  VIEW_PERMISSIONS: "VIEW_PERMISSIONS",

  // System stats
  VIEW_STATS: "VIEW_STATS",

  // Product permissions
  VIEW_PRODUCTS: "VIEW_PRODUCTS",
  CREATE_PRODUCTS: "CREATE_PRODUCTS",
  UPDATE_PRODUCTS: "UPDATE_PRODUCTS",
  DELETE_PRODUCTS: "DELETE_PRODUCTS",

  // Brand-specific product permissions - Project Zero
  VIEW_PRODUCTS_PROJECT_ZERO: "VIEW_PRODUCTS_PROJECT_ZERO",
  CREATE_PRODUCTS_PROJECT_ZERO: "CREATE_PRODUCTS_PROJECT_ZERO",
  UPDATE_PRODUCTS_PROJECT_ZERO: "UPDATE_PRODUCTS_PROJECT_ZERO",
  DELETE_PRODUCTS_PROJECT_ZERO: "DELETE_PRODUCTS_PROJECT_ZERO",

  // Brand-specific product permissions - Thomas Mushet
  VIEW_PRODUCTS_THOMAS_MUSHET: "VIEW_PRODUCTS_THOMAS_MUSHET",
  CREATE_PRODUCTS_THOMAS_MUSHET: "CREATE_PRODUCTS_THOMAS_MUSHET",
  UPDATE_PRODUCTS_THOMAS_MUSHET: "UPDATE_PRODUCTS_THOMAS_MUSHET",
  DELETE_PRODUCTS_THOMAS_MUSHET: "DELETE_PRODUCTS_THOMAS_MUSHET",

  // Brand-specific product permissions - Hear My Voice
  VIEW_PRODUCTS_HEAR_MY_VOICE: "VIEW_PRODUCTS_HEAR_MY_VOICE",
  CREATE_PRODUCTS_HEAR_MY_VOICE: "CREATE_PRODUCTS_HEAR_MY_VOICE",
  UPDATE_PRODUCTS_HEAR_MY_VOICE: "UPDATE_PRODUCTS_HEAR_MY_VOICE",
  DELETE_PRODUCTS_HEAR_MY_VOICE: "DELETE_PRODUCTS_HEAR_MY_VOICE",

  // Stock permissions
  VIEW_STOCK: "VIEW_STOCK",
  CREATE_STOCK: "CREATE_STOCK",
  UPDATE_STOCK: "UPDATE_STOCK",
  DELETE_STOCK: "DELETE_STOCK",

  // Brand-specific stock permissions - Project Zero
  VIEW_STOCK_PROJECT_ZERO: "VIEW_STOCK_PROJECT_ZERO",
  CREATE_STOCK_PROJECT_ZERO: "CREATE_STOCK_PROJECT_ZERO",
  UPDATE_STOCK_PROJECT_ZERO: "UPDATE_STOCK_PROJECT_ZERO",
  DELETE_STOCK_PROJECT_ZERO: "DELETE_STOCK_PROJECT_ZERO",

  // Brand-specific stock permissions - Thomas Mushet
  VIEW_STOCK_THOMAS_MUSHET: "VIEW_STOCK_THOMAS_MUSHET",
  CREATE_STOCK_THOMAS_MUSHET: "CREATE_STOCK_THOMAS_MUSHET",
  UPDATE_STOCK_THOMAS_MUSHET: "UPDATE_STOCK_THOMAS_MUSHET",
  DELETE_STOCK_THOMAS_MUSHET: "DELETE_STOCK_THOMAS_MUSHET",

  // Brand-specific stock permissions - Hear My Voice
  VIEW_STOCK_HEAR_MY_VOICE: "VIEW_STOCK_HEAR_MY_VOICE",
  CREATE_STOCK_HEAR_MY_VOICE: "CREATE_STOCK_HEAR_MY_VOICE",
  UPDATE_STOCK_HEAR_MY_VOICE: "UPDATE_STOCK_HEAR_MY_VOICE",
  DELETE_STOCK_HEAR_MY_VOICE: "DELETE_STOCK_HEAR_MY_VOICE",

  // Sales permissions
  VIEW_SALES: "VIEW_SALES",
  CREATE_SALES: "CREATE_SALES",
  UPDATE_SALES: "UPDATE_SALES",
  DELETE_SALES: "DELETE_SALES",

  // Loyalty points
  CREATE_LOYALTY_POINTS: "CREATE_LOYALTY_POINTS",
  VIEW_LOYALTY_POINTS: "VIEW_LOYALTY_POINTS",
  UPDATE_LOYALTY_POINTS: "UPDATE_LOYALTY_POINTS",
  DELETE_LOYALTY_POINTS: "DELETE_LOYALTY_POINTS",

  // Community posts
  VIEW_COMMUNITY_POSTS: "VIEW_COMMUNITY_POSTS",
  CREATE_COMMUNITY_POSTS: "CREATE_COMMUNITY_POSTS",
  UPDATE_COMMUNITY_POSTS: "UPDATE_COMMUNITY_POSTS",
  DELETE_COMMUNITY_POSTS: "DELETE_COMMUNITY_POSTS",

  // Reviews
  VIEW_REVIEWS: "VIEW_REVIEWS",
  CREATE_REVIEWS: "CREATE_REVIEWS",
  UPDATE_REVIEWS: "UPDATE_REVIEWS",
  DELETE_REVIEWS: "DELETE_REVIEWS",

  // Wishlist
  VIEW_WISHLIST: "VIEW_WISHLIST",
  CREATE_WISHLIST: "CREATE_WISHLIST",
  UPDATE_WISHLIST: "UPDATE_WISHLIST",
  DELETE_WISHLIST: "DELETE_WISHLIST",

  // Cart
  VIEW_CART: "VIEW_CART",
  CREATE_CART: "CREATE_CART",
  UPDATE_CART: "UPDATE_CART",
  DELETE_CART: "DELETE_CART",

  // Admin access
  ADMIN_ACCESS: "ADMIN_ACCESS",
} as const;

export type PermissionName = typeof PERMISSIONS[keyof typeof PERMISSIONS];
